var data = [
{
  "Address": 1050334,
  "AddressString": "001006de",
  "Name": "ForEach",
  "Type": "void*",
  "Other": "void* elms, u32 count, u32 elmSize, void (__convention(\u0022cdecl\u0022)* foo)(void*)",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001006de void* ForEach(void* elms, u32 count, u32 elmSize, void (__convention(\u0022cdecl\u0022)* foo)(void*))"
},
{
  "Address": 1052738,
  "AddressString": "00101042",
  "Name": "Utf16_strlen",
  "Type": "u32",
  "Other": "u16* utf16_str",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00101042 u32 Utf16_strlen(u16* utf16_str)"
},
{
  "Address": 1055580,
  "AddressString": "00101b5c",
  "Name": "Utf16_strcmp",
  "Type": "u32",
  "Other": "u16* str1, u16* str2, u32 length",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00101b5c u32 Utf16_strcmp(u16* str1, u16* str2, u32 length)"
},
{
  "Address": 1129700,
  "AddressString": "00113ce4",
  "Name": "_cfguInit",
  "Type": "int32_t",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00113ce4 int32_t _cfguInit()"
},
{
  "Address": 1135000,
  "AddressString": "00115198",
  "Name": "CreateColour",
  "Type": "void",
  "Other": "Colour* c, u32 R, u32 G, u32 B, u32 A",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00115198 void CreateColour(Colour* c, u32 R, u32 G, u32 B, u32 A)"
},
{
  "Address": 1174652,
  "AddressString": "0011ec7c",
  "Name": "ClearItem2",
  "Type": "void",
  "Other": "Item* item",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0011ec7c void ClearItem2(Item* item)"
},
{
  "Address": 1276964,
  "AddressString": "00137c24",
  "Name": "ShowPopup",
  "Type": "void",
  "Other": "String* string",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00137c24 void ShowPopup(String* string)"
},
{
  "Address": 1292492,
  "AddressString": "0013b8cc",
  "Name": "ClearItem",
  "Type": "void",
  "Other": "Item* item",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0013b8cc void ClearItem(Item* item)"
},
{
  "Address": 1292996,
  "AddressString": "0013bac4",
  "Name": "Main::PlaySound",
  "Type": "void",
  "Other": "s32 soundId",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0013bac4 void Main::PlaySound(s32 soundId)"
},
{
  "Address": 1308992,
  "AddressString": "0013f940",
  "Name": "RandomNumber",
  "Type": "int32_t",
  "Other": "int32_t* arg1, int32_t arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0013f940 int32_t RandomNumber(int32_t* arg1, int32_t arg2)"
},
{
  "Address": 1309108,
  "AddressString": "0013f9b4",
  "Name": "RandomNumberRange",
  "Type": "s32",
  "Other": "int128_t* seed, s32 min, s32 max",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0013f9b4 s32 RandomNumberRange(int128_t* seed, s32 min, s32 max)"
},
{
  "Address": 1326836,
  "AddressString": "00143ef4",
  "Name": "GetPlayer",
  "Type": "Player*",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00143ef4 Player* GetPlayer()"
},
{
  "Address": 1352268,
  "AddressString": "0014a24c",
  "Name": "ClearImageLoader",
  "Type": "ImageLoader*",
  "Other": "ImageLoader* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0014a24c ImageLoader* ClearImageLoader(ImageLoader* arg1)"
},
{
  "Address": 1356768,
  "AddressString": "0014b3e0",
  "Name": "EE::String::Null",
  "Type": "int32_t",
  "Other": "void** arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0014b3e0 int32_t EE::String::Null(void** arg1)"
},
{
  "Address": 1357204,
  "AddressString": "0014b594",
  "Name": "EE::String::~String",
  "Type": "void",
  "Other": "String* str",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0014b594 void EE::String::~String(String* str)"
},
{
  "Address": 1357244,
  "AddressString": "0014b5bc",
  "Name": "EE::String::operator=",
  "Type": "String*",
  "Other": "String* str, String* arg2, void* arg3",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0014b5bc String* EE::String::operator=(String* str, String* arg2, void* arg3)"
},
{
  "Address": 1374136,
  "AddressString": "0014f7b8",
  "Name": "FreeStringType2",
  "Type": "void*",
  "Other": "String* str",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0014f7b8 void* FreeStringType2(String* str)"
},
{
  "Address": 1384592,
  "AddressString": "00152090",
  "Name": "EE::String::String",
  "Type": "String*",
  "Other": "String* str1, char* rawStr",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00152090 String* EE::String::String(String* str1, char* rawStr)"
},
{
  "Address": 1431324,
  "AddressString": "0015d71c",
  "Name": "MurmurHash3",
  "Type": "u32",
  "Other": "String* string, u32 seed",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0015d71c u32 MurmurHash3(String* string, u32 seed)"
},
{
  "Address": 1432820,
  "AddressString": "0015dcf4",
  "Name": "GlyphSet::GetGlyph",
  "Type": "int32_t",
  "Other": "void* arg1, int32_t arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0015dcf4 int32_t GlyphSet::GetGlyph(void* arg1, int32_t arg2)"
},
{
  "Address": 1565684,
  "AddressString": "0017e3f4",
  "Name": "LoadBackground",
  "Type": "void",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0017e3f4 void LoadBackground()"
},
{
  "Address": 1572948,
  "AddressString": "00180054",
  "Name": "DrawBackground",
  "Type": "void",
  "Other": "void* arg1, u32 backgroundType, int32_t arg3, Colour colour1 @ r9, int32_t arg5 @ r11, int32_t arg6, int32_t arg7",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00180054 void DrawBackground(void* arg1, u32 backgroundType, int32_t arg3, Colour colour1 @ r9, int32_t arg5 @ r11, int32_t arg6, int32_t arg7)"
},
{
  "Address": 1749920,
  "AddressString": "001ab3a0",
  "Name": "Projectile::Kill",
  "Type": "uint32_t",
  "Other": "Projectile* projectile, int128_t arg2 @ q0",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001ab3a0 uint32_t Projectile::Kill(Projectile* projectile, int128_t arg2 @ q0)"
},
{
  "Address": 1860256,
  "AddressString": "001c62a0",
  "Name": "ClearProjectile",
  "Type": "void",
  "Other": "Projectile* projectile",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001c62a0 void ClearProjectile(Projectile* projectile)"
},
{
  "Address": 1933356,
  "AddressString": "001d802c",
  "Name": "SoundEffect::Load",
  "Type": "void",
  "Other": "int32_t* arg1, String* str",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001d802c void SoundEffect::Load(int32_t* arg1, String* str)"
},
{
  "Address": 1951888,
  "AddressString": "001dc890",
  "Name": "Underground::LoadContent",
  "Type": "void*",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001dc890 void* Underground::LoadContent()"
},
{
  "Address": 1979940,
  "AddressString": "001e3624",
  "Name": "Achievements::TriggerSystem::ReadProfile",
  "Type": "void",
  "Other": "int32_t arg1, int32_t arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001e3624 void Achievements::TriggerSystem::ReadProfile(int32_t arg1, int32_t arg2)"
},
{
  "Address": 1980012,
  "AddressString": "001e366c",
  "Name": "Achievements::TriggerSystem::UpdateAchievements",
  "Type": "void*",
  "Other": "void* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001e366c void* Achievements::TriggerSystem::UpdateAchievements(void* arg1)"
},
{
  "Address": 1981224,
  "AddressString": "001e3b28",
  "Name": "Achievements::AchievementSystem::Award",
  "Type": "uint32_t",
  "Other": "char* arg1, uint32_t arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001e3b28 uint32_t Achievements::AchievementSystem::Award(char* arg1, uint32_t arg2)"
},
{
  "Address": 2028808,
  "AddressString": "001ef508",
  "Name": "GetIconName",
  "Type": "String*",
  "Other": "String* name, u32 iconType",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001ef508 String* GetIconName(String* name, u32 iconType)"
},
{
  "Address": 2083196,
  "AddressString": "001fc97c",
  "Name": "WidgetLoader::loadSprite",
  "Type": "int32_t*",
  "Other": "void* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001fc97c int32_t* WidgetLoader::loadSprite(void* arg1)"
},
{
  "Address": 2084040,
  "AddressString": "001fccc8",
  "Name": "WidgetLoader::loadWidget",
  "Type": "void***",
  "Other": "void* arg1, int32_t arg2 @ r5",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x001fccc8 void*** WidgetLoader::loadWidget(void* arg1, int32_t arg2 @ r5)"
},
{
  "Address": 2105848,
  "AddressString": "002021f8",
  "Name": "WidgetLoader::load",
  "Type": "int32_t",
  "Other": "int32_t* arg1, void* arg2 @ r4, int32_t arg3 @ r5",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002021f8 int32_t WidgetLoader::load(int32_t* arg1, void* arg2 @ r4, int32_t arg3 @ r5)"
},
{
  "Address": 2231132,
  "AddressString": "00220b5c",
  "Name": "QuestFishTypeToId",
  "Type": "s32",
  "Other": "u32 questID",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00220b5c s32 QuestFishTypeToId(u32 questID)"
},
{
  "Address": 2325308,
  "AddressString": "00237b3c",
  "Name": "LoadSound",
  "Type": "void",
  "Other": "SoundEffect* sound, String* str, int32_t arg3",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00237b3c void LoadSound(SoundEffect* sound, String* str, int32_t arg3)"
},
{
  "Address": 2325584,
  "AddressString": "00237c50",
  "Name": "LoadSound2",
  "Type": "void",
  "Other": "SoundEffect* sound, String* str, int32_t arg3",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00237c50 void LoadSound2(SoundEffect* sound, String* str, int32_t arg3)"
},
{
  "Address": 2325868,
  "AddressString": "00237d6c",
  "Name": "ClearSoundEffect",
  "Type": "void",
  "Other": "SoundEffect* sound",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00237d6c void ClearSoundEffect(SoundEffect* sound)"
},
{
  "Address": 2383928,
  "AddressString": "00246038",
  "Name": "en_str[0x3]",
  "Type": "char",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "00246038 char en_str[0x3]"
},
{
  "Address": 2459884,
  "AddressString": "002588ec",
  "Name": "ReleaseNPC",
  "Type": "void",
  "Other": "s32 X, s32 Y, s32 npcId, u32 style, s32 who",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002588ec void ReleaseNPC(s32 X, s32 Y, s32 npcId, u32 style, s32 who)"
},
{
  "Address": 2476412,
  "AddressString": "0025c97c",
  "Name": "NPC::SpawnFriendlyNPC",
  "Type": "u32",
  "Other": "int32_t* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0025c97c u32 NPC::SpawnFriendlyNPC(int32_t* arg1)"
},
{
  "Address": 2477984,
  "AddressString": "0025cfa0",
  "Name": "setFireFlyChance",
  "Type": "void",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0025cfa0 void setFireFlyChance()"
},
{
  "Address": 2597068,
  "AddressString": "0027a0cc",
  "Name": "KillFrostLegionEnemy",
  "Type": "void",
  "Other": "int32_t arg1, NPC* npc",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0027a0cc void KillFrostLegionEnemy(int32_t arg1, NPC* npc)"
},
{
  "Address": 2704864,
  "AddressString": "002945e0",
  "Name": "EE::String::Format",
  "Type": "String*",
  "Other": "String* destStr, char* formatStr, void* args",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002945e0 String* EE::String::Format(String* destStr, char* formatStr, void* args)"
},
{
  "Address": 2705100,
  "AddressString": "002946cc",
  "Name": "LoadString",
  "Type": "String*",
  "Other": "String* arg1, String* dest, char* raw",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002946cc String* LoadString(String* arg1, String* dest, char* raw)"
},
{
  "Address": 2719968,
  "AddressString": "002980e0",
  "Name": "UI::UpdateNpcChat",
  "Type": "int32_t",
  "Other": "PlayerParentPlaceholder* arg1, int32_t arg2 @ r4",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002980e0 int32_t UI::UpdateNpcChat(PlayerParentPlaceholder* arg1, int32_t arg2 @ r4)"
},
{
  "Address": 2741716,
  "AddressString": "0029d5d4",
  "Name": "UI::HelpText",
  "Type": "void",
  "Other": "PlayerParentPlaceholder* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0029d5d4 void UI::HelpText(PlayerParentPlaceholder* arg1)"
},
{
  "Address": 2750552,
  "AddressString": "0029f858",
  "Name": "TownNPCFromId",
  "Type": "s32",
  "Other": "void* arg1, s32 npcId",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0029f858 s32 TownNPCFromId(void* arg1, s32 npcId)"
},
{
  "Address": 2820172,
  "AddressString": "002b084c",
  "Name": "_cfguExit2",
  "Type": "void",
  "Other": "int32_t arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002b084c void _cfguExit2(int32_t arg1)"
},
{
  "Address": 2826568,
  "AddressString": "002b2148",
  "Name": "_cfguExit",
  "Type": "int32_t",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002b2148 int32_t _cfguExit()"
},
{
  "Address": 3126752,
  "AddressString": "002fb5e0",
  "Name": "StringLength",
  "Type": "u32",
  "Other": "char* raw",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002fb5e0 u32 StringLength(char* raw)"
},
{
  "Address": 3127720,
  "AddressString": "002fb9a8",
  "Name": "SetStringTypeString",
  "Type": "String*",
  "Other": "String* strType, char* rawStr",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002fb9a8 String* SetStringTypeString(String* strType, char* rawStr)"
},
{
  "Address": 3127844,
  "AddressString": "002fba24",
  "Name": "FreeStringType4_2",
  "Type": "String*",
  "Other": "String* str",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002fba24 String* FreeStringType4_2(String* str)"
},
{
  "Address": 3127852,
  "AddressString": "002fba2c",
  "Name": "FreeStringType4",
  "Type": "String*",
  "Other": "String* str",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002fba2c String* FreeStringType4(String* str)"
},
{
  "Address": 3129254,
  "AddressString": "002fbfa6",
  "Name": "Memcpy_aligned2",
  "Type": "char*",
  "Other": "char* dest, char* src, u32 length, void* arg4",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002fbfa6 char* Memcpy_aligned2(char* dest, char* src, u32 length, void* arg4)"
},
{
  "Address": 3135772,
  "AddressString": "002fd91c",
  "Name": "Memcpy_aligned",
  "Type": "void",
  "Other": "char* dest, char* src, u32 length, void* arg4, void* arg5 @ r12",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002fd91c void Memcpy_aligned(char* dest, char* src, u32 length, void* arg4, void* arg5 @ r12)"
},
{
  "Address": 3135932,
  "AddressString": "002fd9bc",
  "Name": "FreeString3_2",
  "Type": "void*",
  "Other": "String* str",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002fd9bc void* FreeString3_2(String* str)"
},
{
  "Address": 3135940,
  "AddressString": "002fd9c4",
  "Name": "FreeStringType3",
  "Type": "void*",
  "Other": "String* str",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x002fd9c4 void* FreeStringType3(String* str)"
},
{
  "Address": 3148556,
  "AddressString": "00300b0c",
  "Name": "CheckOnce",
  "Type": "bool",
  "Other": "bool* flag",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00300b0c bool CheckOnce(bool* flag)"
},
{
  "Address": 3320488,
  "AddressString": "0032aaa8",
  "Name": "Cue::Load",
  "Type": "int32_t",
  "Other": "void* arg1, int32_t* arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0032aaa8 int32_t Cue::Load(void* arg1, int32_t* arg2)"
},
{
  "Address": 3322064,
  "AddressString": "0032b0d0",
  "Name": "Cue::IsPlaying",
  "Type": "int32_t",
  "Other": "void* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0032b0d0 int32_t Cue::IsPlaying(void* arg1)"
},
{
  "Address": 3337560,
  "AddressString": "0032ed58",
  "Name": "NPC::SpawnBunny",
  "Type": "u32",
  "Other": "s32 X, s32 Y",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0032ed58 u32 NPC::SpawnBunny(s32 X, s32 Y)"
},
{
  "Address": 3361912,
  "AddressString": "00334c78",
  "Name": "NPCToBanner",
  "Type": "s32",
  "Other": "s32 npcId",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00334c78 s32 NPCToBanner(s32 npcId)"
},
{
  "Address": 3370040,
  "AddressString": "00336c38",
  "Name": "SetDefaults_NPC",
  "Type": "int32_t",
  "Other": "NPC* npc, u16 npcId @ r11, int32_t arg3, int32_t arg4",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00336c38 int32_t SetDefaults_NPC(NPC* npc, u16 npcId @ r11, int32_t arg3, int32_t arg4)"
},
{
  "Address": 3416196,
  "AddressString": "00342084",
  "Name": "SetDefaultName_NPC",
  "Type": "uint16_t",
  "Other": "void* npc, String* npcName",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00342084 uint16_t SetDefaultName_NPC(void* npc, String* npcName)"
},
{
  "Address": 3460532,
  "AddressString": "0034cdb4",
  "Name": "SpawnSnowmanEnemy",
  "Type": "u32",
  "Other": "int32_t arg1 @ r4, int32_t arg2 @ r8",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0034cdb4 u32 SpawnSnowmanEnemy(int32_t arg1 @ r4, int32_t arg2 @ r8)"
},
{
  "Address": 3460668,
  "AddressString": "0034ce3c",
  "Name": "SpawnLiquidNPC",
  "Type": "u32",
  "Other": "int32_t* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0034ce3c u32 SpawnLiquidNPC(int32_t* arg1)"
},
{
  "Address": 3466140,
  "AddressString": "0034e39c",
  "Name": "GetNPCIndex",
  "Type": "s32",
  "Other": "s32 npcId",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0034e39c s32 GetNPCIndex(s32 npcId)"
},
{
  "Address": 3467048,
  "AddressString": "0034e728",
  "Name": "CountNPCs2",
  "Type": "u32",
  "Other": "u32 npcId",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0034e728 u32 CountNPCs2(u32 npcId)"
},
{
  "Address": 3467052,
  "AddressString": "0034e72c",
  "Name": "NPC::AnyNPCs",
  "Type": "u32",
  "Other": "u32 npcId",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0034e72c u32 NPC::AnyNPCs(u32 npcId)"
},
{
  "Address": 3474576,
  "AddressString": "00350490",
  "Name": "NPC::SpawnUniqueNPC",
  "Type": "u32",
  "Other": "int32_t* arg1, int32_t arg2 @ r4, int32_t arg3 @ r5",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00350490 u32 NPC::SpawnUniqueNPC(int32_t* arg1, int32_t arg2 @ r4, int32_t arg3 @ r5)"
},
{
  "Address": 3615772,
  "AddressString": "00372c1c",
  "Name": "NPC::SpawnPositionBasedNPC",
  "Type": "u32",
  "Other": "int32_t* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00372c1c u32 NPC::SpawnPositionBasedNPC(int32_t* arg1)"
},
{
  "Address": 3659704,
  "AddressString": "0037d7b8",
  "Name": "NPC::NewNPC",
  "Type": "u32",
  "Other": "s32 X, s32 Y, s32 npcId, int32_t arg4, int32_t arg5 @ r4",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0037d7b8 u32 NPC::NewNPC(s32 X, s32 Y, s32 npcId, int32_t arg4, int32_t arg5 @ r4)"
},
{
  "Address": 3674892,
  "AddressString": "0038130c",
  "Name": "AnyNPCs",
  "Type": "bool",
  "Other": "u32 npcId",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0038130c bool AnyNPCs(u32 npcId)"
},
{
  "Address": 3702092,
  "AddressString": "00387d4c",
  "Name": "NPCLoot",
  "Type": "void",
  "Other": "NPC* npc",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00387d4c void NPCLoot(NPC* npc)"
},
{
  "Address": 3750728,
  "AddressString": "00393b48",
  "Name": "SpawnWOF",
  "Type": "void",
  "Other": "Vector2 pos",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00393b48 void SpawnWOF(Vector2 pos)"
},
{
  "Address": 3851924,
  "AddressString": "003ac694",
  "Name": "SetDefaultName_Item",
  "Type": "int32_t",
  "Other": "Item* arg1, String* itemName @ r9",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003ac694 int32_t SetDefaultName_Item(Item* arg1, String* itemName @ r9)"
},
{
  "Address": 3858396,
  "AddressString": "003adfdc",
  "Name": "SetDefault_Item",
  "Type": "void",
  "Other": "Item* arg1, u32 id, u32 stack",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003adfdc void SetDefault_Item(Item* arg1, u32 id, u32 stack)"
},
{
  "Address": 3955744,
  "AddressString": "003c5c20",
  "Name": "NetDefaults_Item",
  "Type": "void",
  "Other": "Item* item, s32 id, u32 stack",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003c5c20 void NetDefaults_Item(Item* item, s32 id, u32 stack)"
},
{
  "Address": 3962612,
  "AddressString": "003c76f4",
  "Name": "MergeItems",
  "Type": "u32",
  "Other": "Item* item1, Item* item2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003c76f4 u32 MergeItems(Item* item1, Item* item2)"
},
{
  "Address": 3962816,
  "AddressString": "003c77c0",
  "Name": "Prefix_Item",
  "Type": "bool",
  "Other": "Item* item, s32 prefix, int128_t arg3 @ q4",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003c77c0 bool Prefix_Item(Item* item, s32 prefix, int128_t arg3 @ q4)"
},
{
  "Address": 3970676,
  "AddressString": "003c9674",
  "Name": "NewItem_Item",
  "Type": "u32",
  "Other": "u32 X, u32 Y, s32 width, s32 height, u32 id, u32 stack, int32_t arg7, s32 prefix, int32_t arg9",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003c9674 u32 NewItem_Item(u32 X, u32 Y, s32 width, s32 height, u32 id, u32 stack, int32_t arg7, s32 prefix, int32_t arg9)"
},
{
  "Address": 3972652,
  "AddressString": "003c9e2c",
  "Name": "GetValueSell",
  "Type": "u32",
  "Other": "u32 platinum, u32 gold, u32 silver, u32 copper",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003c9e2c u32 GetValueSell(u32 platinum, u32 gold, u32 silver, u32 copper)"
},
{
  "Address": 3973520,
  "AddressString": "003ca190",
  "Name": "GetValueBuy",
  "Type": "u32",
  "Other": "u32 platinum, u32 gold, u32 silver, u32 copper",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003ca190 u32 GetValueBuy(u32 platinum, u32 gold, u32 silver, u32 copper)"
},
{
  "Address": 4007396,
  "AddressString": "003d25e4",
  "Name": "Main::LoadContent",
  "Type": "int32_t",
  "Other": "void* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003d25e4 int32_t Main::LoadContent(void* arg1)"
},
{
  "Address": 4010908,
  "AddressString": "003d339c",
  "Name": "DoCommand",
  "Type": "uint32_t",
  "Other": "String* command @ r7",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003d339c uint32_t DoCommand(String* command @ r7)"
},
{
  "Address": 4035332,
  "AddressString": "003d9304",
  "Name": "Main::LoadingThread",
  "Type": "void",
  "Other": "void* mainInstance",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003d9304 void Main::LoadingThread(void* mainInstance)"
},
{
  "Address": 4046608,
  "AddressString": "003dbf10",
  "Name": "Main::PlayMusic",
  "Type": "int32_t",
  "Other": "int32_t arg1, int32_t arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003dbf10 int32_t Main::PlayMusic(int32_t arg1, int32_t arg2)"
},
{
  "Address": 4046772,
  "AddressString": "003dbfb4",
  "Name": "Main::PlaySound_At",
  "Type": "void",
  "Other": "u32 type, u32 X, u32 Y, u32 style",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003dbfb4 void Main::PlaySound_At(u32 type, u32 X, u32 Y, u32 style)"
},
{
  "Address": 4050532,
  "AddressString": "003dce64",
  "Name": "Main::Main",
  "Type": "void**",
  "Other": "void** arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003dce64 void** Main::Main(void** arg1)"
},
{
  "Address": 4098164,
  "AddressString": "003e8874",
  "Name": "Time::IsEaster",
  "Type": "bool",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003e8874 bool Time::IsEaster()"
},
{
  "Address": 4100228,
  "AddressString": "003e9084",
  "Name": "Time::IsHalloween",
  "Type": "bool",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003e9084 bool Time::IsHalloween()"
},
{
  "Address": 4100296,
  "AddressString": "003e90c8",
  "Name": "IsValentinesDay",
  "Type": "bool",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003e90c8 bool IsValentinesDay()"
},
{
  "Address": 4101068,
  "AddressString": "003e93cc",
  "Name": "IsOktoberfest",
  "Type": "bool",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003e93cc bool IsOktoberfest()"
},
{
  "Address": 4101136,
  "AddressString": "003e9410",
  "Name": "IsThanksgiving",
  "Type": "bool",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003e9410 bool IsThanksgiving()"
},
{
  "Address": 4102016,
  "AddressString": "003e9780",
  "Name": "Time::IsChristmas",
  "Type": "bool",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003e9780 bool Time::IsChristmas()"
},
{
  "Address": 4156368,
  "AddressString": "003f6bd0",
  "Name": "SetupShop",
  "Type": "uint32_t",
  "Other": "Chest* inv, u32 npcType, Player* player",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003f6bd0 uint32_t SetupShop(Chest* inv, u32 npcType, Player* player)"
},
{
  "Address": 4165696,
  "AddressString": "003f9040",
  "Name": "ClearChest",
  "Type": "void",
  "Other": "Chest* chest",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003f9040 void ClearChest(Chest* chest)"
},
{
  "Address": 4191380,
  "AddressString": "003ff494",
  "Name": "Mount::Initialize",
  "Type": "int32_t",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x003ff494 int32_t Mount::Initialize()"
},
{
  "Address": 4195808,
  "AddressString": "004005e0",
  "Name": "Mount::AnimState::AnimState",
  "Type": "void",
  "Other": "int32_t* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004005e0 void Mount::AnimState::AnimState(int32_t* arg1)"
},
{
  "Address": 4195832,
  "AddressString": "004005f8",
  "Name": "Mount::MountData::MountData",
  "Type": "int32_t",
  "Other": "void* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004005f8 int32_t Mount::MountData::MountData(void* arg1)"
},
{
  "Address": 4242992,
  "AddressString": "0040be30",
  "Name": "UpdatePlayer",
  "Type": "void",
  "Other": "Player* player, u32 playerId",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0040be30 void UpdatePlayer(Player* player, u32 playerId)"
},
{
  "Address": 4488156,
  "AddressString": "00447bdc",
  "Name": "SetupRecipes",
  "Type": "void",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00447bdc void SetupRecipes()"
},
{
  "Address": 4534364,
  "AddressString": "0045305c",
  "Name": "SetupRecipes2",
  "Type": "void",
  "Other": "Item* arg1 @ r5, Item* arg2 @ r6, Item* arg3 @ r7, char* arg4 @ r10",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0045305c void SetupRecipes2(Item* arg1 @ r5, Item* arg2 @ r6, Item* arg3 @ r7, char* arg4 @ r10)"
},
{
  "Address": 4558916,
  "AddressString": "00459044",
  "Name": "SetupRecipes3",
  "Type": "void",
  "Other": "void* arg1 @ r4, Item* arg2 @ r5, Item* arg3 @ r6, Item* arg4 @ r7, char* arg5 @ r8, int16_t arg6 @ r9, int32_t arg7 @ r10, int32_t arg8, int32_t arg9, int32_t arg10, int32_t arg11, int32_t arg12, int32_t arg13, int32_t arg14, int32_t arg15, int32_t arg16",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00459044 void SetupRecipes3(void* arg1 @ r4, Item* arg2 @ r5, Item* arg3 @ r6, Item* arg4 @ r7, char* arg5 @ r8, int16_t arg6 @ r9, int32_t arg7 @ r10, int32_t arg8, int32_t arg9, int32_t arg10, int32_t arg11, int32_t arg12, int32_t arg13, int32_t arg14, int32_t arg15, int32_t arg16)"
},
{
  "Address": 4563272,
  "AddressString": "0045a148",
  "Name": "AddRecipe",
  "Type": "void",
  "Other": "void* arg1, void* arg2, void* arg3, void* arg4",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0045a148 void AddRecipe(void* arg1, void* arg2, void* arg3, void* arg4)"
},
{
  "Address": 4607924,
  "AddressString": "00464fb4",
  "Name": "SetNpcCatchable",
  "Type": "void",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00464fb4 void SetNpcCatchable()"
},
{
  "Address": 4640660,
  "AddressString": "0046cf94",
  "Name": "GetAnglerReward",
  "Type": "int32_t",
  "Other": "Player* player",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0046cf94 int32_t GetAnglerReward(Player* player)"
},
{
  "Address": 4646960,
  "AddressString": "0046e830",
  "Name": "GetQuestFishId",
  "Type": "u32",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0046e830 u32 GetQuestFishId()"
},
{
  "Address": 4653200,
  "AddressString": "00470090",
  "Name": "LoadWorldFileHeader2",
  "Type": "void",
  "Other": "FileReader* reader, int32_t arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00470090 void LoadWorldFileHeader2(FileReader* reader, int32_t arg2)"
},
{
  "Address": 4695676,
  "AddressString": "0047a67c",
  "Name": "XMLFile::readString",
  "Type": "int32_t",
  "Other": "int32_t arg1, void* arg2, int32_t* arg3",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0047a67c int32_t XMLFile::readString(int32_t arg1, void* arg2, int32_t* arg3)"
},
{
  "Address": 4697316,
  "AddressString": "0047ace4",
  "Name": "XMLFile::getAttribute",
  "Type": "int32_t",
  "Other": "int32_t arg1, void* arg2, int32_t* arg3",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0047ace4 int32_t XMLFile::getAttribute(int32_t arg1, void* arg2, int32_t* arg3)"
},
{
  "Address": 4703896,
  "AddressString": "0047c698",
  "Name": "XMLFile::gotoNode",
  "Type": "int32_t",
  "Other": "void* arg1, int32_t arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0047c698 int32_t XMLFile::gotoNode(void* arg1, int32_t arg2)"
},
{
  "Address": 4704020,
  "AddressString": "0047c714",
  "Name": "XMLFile::hasChild",
  "Type": "int32_t*",
  "Other": "void* arg1, int32_t* arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0047c714 int32_t* XMLFile::hasChild(void* arg1, int32_t* arg2)"
},
{
  "Address": 4704064,
  "AddressString": "0047c740",
  "Name": "XMLFile::readBool",
  "Type": "int32_t",
  "Other": "void* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0047c740 int32_t XMLFile::readBool(void* arg1)"
},
{
  "Address": 4704464,
  "AddressString": "0047c8d0",
  "Name": "XMLFile::gotoChild",
  "Type": "int32_t",
  "Other": "void* arg1, int32_t* arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0047c8d0 int32_t XMLFile::gotoChild(void* arg1, int32_t* arg2)"
},
{
  "Address": 4704576,
  "AddressString": "0047c940",
  "Name": "XMLFile::gotoStart",
  "Type": "int32_t",
  "Other": "void* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0047c940 int32_t XMLFile::gotoStart(void* arg1)"
},
{
  "Address": 4775984,
  "AddressString": "0048e030",
  "Name": "DrawItemSlot",
  "Type": "int32_t*",
  "Other": "Draw_Unk2* arg1, int32_t* arg2, s32 num1, String* str1, int32_t arg5",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0048e030 int32_t* DrawItemSlot(Draw_Unk2* arg1, int32_t* arg2, s32 num1, String* str1, int32_t arg5)"
},
{
  "Address": 4855716,
  "AddressString": "004a17a4",
  "Name": "ClearWorld",
  "Type": "void",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004a17a4 void ClearWorld()"
},
{
  "Address": 4889372,
  "AddressString": "004a9b1c",
  "Name": "WorldGen::GrowPumpkin",
  "Type": "void",
  "Other": "u32 X, u32 Y, s32 id",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004a9b1c void WorldGen::GrowPumpkin(u32 X, u32 Y, s32 id)"
},
{
  "Address": 4945376,
  "AddressString": "004b75e0",
  "Name": "PlacePumpkin",
  "Type": "void",
  "Other": "u32 X, u32 Y",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004b75e0 void PlacePumpkin(u32 X, u32 Y)"
},
{
  "Address": 4965712,
  "AddressString": "004bc550",
  "Name": "GenerateWorld",
  "Type": "int32_t",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004bc550 int32_t GenerateWorld()"
},
{
  "Address": 5027292,
  "AddressString": "004cb5dc",
  "Name": "LoadWorldFileHeader",
  "Type": "void",
  "Other": "FileReader* reader, int32_t arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004cb5dc void LoadWorldFileHeader(FileReader* reader, int32_t arg2)"
},
{
  "Address": 5067420,
  "AddressString": "004d529c",
  "Name": "LoadWorldFileHeader2",
  "Type": "void",
  "Other": "FileReader* reader, int32_t arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004d529c void LoadWorldFileHeader2(FileReader* reader, int32_t arg2)"
},
{
  "Address": 5087868,
  "AddressString": "004da27c",
  "Name": "RandomBackgrounds",
  "Type": "void",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004da27c void RandomBackgrounds()"
},
{
  "Address": 5235176,
  "AddressString": "004fe1e8",
  "Name": "LoadWorld",
  "Type": "void",
  "Other": "FileReader* reader",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x004fe1e8 void LoadWorld(FileReader* reader)"
},
{
  "Address": 5307548,
  "AddressString": "0050fc9c",
  "Name": "GameState::GameState",
  "Type": "void*",
  "Other": "void* arg1",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x0050fc9c void* GameState::GameState(void* arg1)"
},
{
  "Address": 5393484,
  "AddressString": "00524c4c",
  "Name": "ShopItemSlotCount",
  "Type": "s32",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00524c4c s32 ShopItemSlotCount()"
},
{
  "Address": 5395180,
  "AddressString": "005252ec",
  "Name": "StringCompare",
  "Type": "bool",
  "Other": "String* str1, char* rawString",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x005252ec bool StringCompare(String* str1, char* rawString)"
},
{
  "Address": 5450388,
  "AddressString": "00532a94",
  "Name": "PlayerHasQuestFish",
  "Type": "bool",
  "Other": "int32_t arg1, Player* arg2",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00532a94 bool PlayerHasQuestFish(int32_t arg1, Player* arg2)"
},
{
  "Address": 5450416,
  "AddressString": "00532ab0",
  "Name": "PlayerHasItem",
  "Type": "bool",
  "Other": "Player* player, u32 itemId",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00532ab0 bool PlayerHasItem(Player* player, u32 itemId)"
},
{
  "Address": 5585640,
  "AddressString": "00553ae8",
  "Name": "ClearAll",
  "Type": "uint32_t",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x00553ae8 uint32_t ClearAll()"
},
{
  "Address": 5913800,
  "AddressString": "005a3cc8",
  "Name": "GetImageLoader",
  "Type": "ImageLoader*",
  "Other": "",
  "IsFunction": true,
  "IsCodeVariable": true,
  "IsUserDefined": true,
  "ToStringValue": "0x005a3cc8 ImageLoader* GetImageLoader()"
},
{
  "Address": 6493788,
  "AddressString": "0063165c",
  "Name": "fireFlyFriendly_NPC",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063165c u32 fireFlyFriendly_NPC"
},
{
  "Address": 6493792,
  "AddressString": "00631660",
  "Name": "fireFlyChance_NPC",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00631660 u32 fireFlyChance_NPC"
},
{
  "Address": 6493796,
  "AddressString": "00631664",
  "Name": "fireFlyMultiple_NPC",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00631664 u32 fireFlyMultiple_NPC"
},
{
  "Address": 6493800,
  "AddressString": "00631668",
  "Name": "butterflyChance_NPC",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00631668 u32 butterflyChance_NPC"
},
{
  "Address": 6494828,
  "AddressString": "00631a6c",
  "Name": "questFishType",
  "Type": "u8",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00631a6c u8 questFishType"
},
{
  "Address": 6495384,
  "AddressString": "00631c98",
  "Name": "cloudBGActive",
  "Type": "float",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00631c98 float cloudBGActive"
},
{
  "Address": 6495676,
  "AddressString": "00631dbc",
  "Name": "GameState::Terraria",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00631dbc u32 GameState::Terraria"
},
{
  "Address": 6495680,
  "AddressString": "00631dc0",
  "Name": "GameState::terrariaLoader",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00631dc0 u32 GameState::terrariaLoader"
},
{
  "Address": 6498714,
  "AddressString": "0063299a",
  "Name": "NPC::downedGoblins",
  "Type": "bool",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063299a bool NPC::downedGoblins"
},
{
  "Address": 6498717,
  "AddressString": "0063299d",
  "Name": "NPC::downedRabbit",
  "Type": "bool",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063299d bool NPC::downedRabbit"
},
{
  "Address": 6498724,
  "AddressString": "006329a4",
  "Name": "planteraDown",
  "Type": "bool",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "006329a4 bool planteraDown"
},
{
  "Address": 6500398,
  "AddressString": "0063302e",
  "Name": "mouseTextColor",
  "Type": "u8",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063302e u8 mouseTextColor"
},
{
  "Address": 6500634,
  "AddressString": "0063311a",
  "Name": "WorldGen::shadowOrbSmashed",
  "Type": "bool",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063311a bool WorldGen::shadowOrbSmashed"
},
{
  "Address": 6500641,
  "AddressString": "00633121",
  "Name": "crimsonWorld",
  "Type": "char",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00633121 char crimsonWorld"
},
{
  "Address": 6500668,
  "AddressString": "0063313c",
  "Name": "copperType",
  "Type": "int16_t",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063313c int16_t copperType"
},
{
  "Address": 6500670,
  "AddressString": "0063313e",
  "Name": "ironType",
  "Type": "u16",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063313e u16 ironType"
},
{
  "Address": 6500672,
  "AddressString": "00633140",
  "Name": "silverType",
  "Type": "u16",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00633140 u16 silverType"
},
{
  "Address": 6500674,
  "AddressString": "00633142",
  "Name": "goldType",
  "Type": "u16",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00633142 u16 goldType"
},
{
  "Address": 6500680,
  "AddressString": "00633148",
  "Name": "coboltType",
  "Type": "s16",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00633148 s16 coboltType"
},
{
  "Address": 6500682,
  "AddressString": "0063314a",
  "Name": "mythrilType",
  "Type": "s16",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063314a s16 mythrilType"
},
{
  "Address": 6500684,
  "AddressString": "0063314c",
  "Name": "adamantiteType",
  "Type": "u16",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063314c u16 adamantiteType"
},
{
  "Address": 6500686,
  "AddressString": "0063314e",
  "Name": "worldWidth_2",
  "Type": "u16",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063314e u16 worldWidth_2"
},
{
  "Address": 6500688,
  "AddressString": "00633150",
  "Name": "worldHeight_2",
  "Type": "u16",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00633150 u16 worldHeight_2"
},
{
  "Address": 6500704,
  "AddressString": "00633160",
  "Name": "treeBG_WorldGen",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00633160 u32 treeBG_WorldGen"
},
{
  "Address": 6500716,
  "AddressString": "0063316c",
  "Name": "snowBG_WorldGen",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063316c u32 snowBG_WorldGen"
},
{
  "Address": 6501278,
  "AddressString": "0063339e",
  "Name": "Main::hardMode",
  "Type": "bool",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0063339e bool Main::hardMode"
},
{
  "Address": 6501280,
  "AddressString": "006333a0",
  "Name": "Main::isHDTV",
  "Type": "bool",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "006333a0 bool Main::isHDTV"
},
{
  "Address": 6501286,
  "AddressString": "006333a6",
  "Name": "worldWidth",
  "Type": "u16",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "006333a6 u16 worldWidth"
},
{
  "Address": 6501288,
  "AddressString": "006333a8",
  "Name": "worldHeight",
  "Type": "int16_t",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "006333a8 int16_t worldHeight"
},
{
  "Address": 6501368,
  "AddressString": "006333f8",
  "Name": "Main::worldSurface",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "006333f8 u32 Main::worldSurface"
},
{
  "Address": 6501384,
  "AddressString": "00633408",
  "Name": "myPlayer_Main",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00633408 u32 myPlayer_Main"
},
{
  "Address": 6501424,
  "AddressString": "00633430",
  "Name": "Main::AchievementSystem",
  "Type": "void*",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00633430 void* Main::AchievementSystem"
},
{
  "Address": 6507468,
  "AddressString": "00634bcc",
  "Name": "cfgu_RefCount",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00634bcc u32 cfgu_RefCount"
},
{
  "Address": 8101732,
  "AddressString": "007b9f64",
  "Name": "BackgroundPointers[0xa]",
  "Type": "void*",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "007b9f64 void* BackgroundPointers[0xa]"
},
{
  "Address": 8101772,
  "AddressString": "007b9f8c",
  "Name": "NPC_catchable[0x406]",
  "Type": "bool",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "007b9f8c bool NPC_catchable[0x406]"
},
{
  "Address": 8103772,
  "AddressString": "007ba75c",
  "Name": "Underground::backgroundTexture",
  "Type": "void*",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "007ba75c void* Underground::backgroundTexture"
},
{
  "Address": 8110436,
  "AddressString": "007bc164",
  "Name": "randomNumSeed",
  "Type": "int128_t",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "007bc164 int128_t randomNumSeed"
},
{
  "Address": 8143584,
  "AddressString": "007c42e0",
  "Name": "newRecipe",
  "Type": "Recipe",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "007c42e0 Recipe newRecipe"
},
{
  "Address": 8738460,
  "AddressString": "0085569c",
  "Name": "seed_genRand_WorldGen",
  "Type": "int128_t",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0085569c int128_t seed_genRand_WorldGen"
},
{
  "Address": 8739860,
  "AddressString": "00855c14",
  "Name": "townNpcInvs[0x12]",
  "Type": "Chest",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00855c14 Chest townNpcInvs[0x12]"
},
{
  "Address": 8835044,
  "AddressString": "0086cfe4",
  "Name": "itemArr_1[0x5]",
  "Type": "Item",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0086cfe4 Item itemArr_1[0x5]"
},
{
  "Address": 8835704,
  "AddressString": "0086d278",
  "Name": "drawer_1",
  "Type": "Draw_Unk3",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0086d278 Draw_Unk3 drawer_1"
},
{
  "Address": 8967060,
  "AddressString": "0088d394",
  "Name": "seed_rand_Main",
  "Type": "int128_t",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d394 int128_t seed_rand_Main"
},
{
  "Address": 8967104,
  "AddressString": "0088d3c0",
  "Name": "soundMech",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d3c0 SoundEffect soundMech"
},
{
  "Address": 8967132,
  "AddressString": "0088d3dc",
  "Name": "soundDig_1",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d3dc SoundEffect soundDig_1"
},
{
  "Address": 8967160,
  "AddressString": "0088d3f8",
  "Name": "soundDig_2",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d3f8 SoundEffect soundDig_2"
},
{
  "Address": 8967188,
  "AddressString": "0088d414",
  "Name": "soundDig_3",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d414 SoundEffect soundDig_3"
},
{
  "Address": 8967216,
  "AddressString": "0088d430",
  "Name": "soundTink_1",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d430 SoundEffect soundTink_1"
},
{
  "Address": 8967244,
  "AddressString": "0088d44c",
  "Name": "soundTink_2",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d44c SoundEffect soundTink_2"
},
{
  "Address": 8967272,
  "AddressString": "0088d468",
  "Name": "soundTink_3",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d468 SoundEffect soundTink_3"
},
{
  "Address": 8967300,
  "AddressString": "0088d484",
  "Name": "soundPlayerHit_1",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d484 SoundEffect soundPlayerHit_1"
},
{
  "Address": 8967328,
  "AddressString": "0088d4a0",
  "Name": "soundPlayerHit_2",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d4a0 SoundEffect soundPlayerHit_2"
},
{
  "Address": 8967356,
  "AddressString": "0088d4bc",
  "Name": "soundPlayerHit_3",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d4bc SoundEffect soundPlayerHit_3"
},
{
  "Address": 8967384,
  "AddressString": "0088d4d8",
  "Name": "soundPlayerHitFemail_1",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d4d8 SoundEffect soundPlayerHitFemail_1"
},
{
  "Address": 8967412,
  "AddressString": "0088d4f4",
  "Name": "soundPlayerHitFemail_2",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d4f4 SoundEffect soundPlayerHitFemail_2"
},
{
  "Address": 8967440,
  "AddressString": "0088d510",
  "Name": "soundPlayerHitFemail_3",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d510 SoundEffect soundPlayerHitFemail_3"
},
{
  "Address": 8967468,
  "AddressString": "0088d52c",
  "Name": "soundPlayerKilled",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d52c SoundEffect soundPlayerKilled"
},
{
  "Address": 8967496,
  "AddressString": "0088d548",
  "Name": "soundGrass",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d548 SoundEffect soundGrass"
},
{
  "Address": 8967524,
  "AddressString": "0088d564",
  "Name": "soundGrab",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d564 SoundEffect soundGrab"
},
{
  "Address": 8967552,
  "AddressString": "0088d580",
  "Name": "soundPixie",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d580 SoundEffect soundPixie"
},
{
  "Address": 8967580,
  "AddressString": "0088d59c",
  "Name": "soundItem[0x38]",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088d59c SoundEffect soundItem[0x38]"
},
{
  "Address": 8969148,
  "AddressString": "0088dbbc",
  "Name": "soundNPCHit[0xe]",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088dbbc SoundEffect soundNPCHit[0xe]"
},
{
  "Address": 8969540,
  "AddressString": "0088dd44",
  "Name": "soundNPCKilled[0x14]",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088dd44 SoundEffect soundNPCKilled[0x14]"
},
{
  "Address": 8970100,
  "AddressString": "0088df74",
  "Name": "soundDoorOpen",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088df74 SoundEffect soundDoorOpen"
},
{
  "Address": 8970128,
  "AddressString": "0088df90",
  "Name": "soundDoorClose",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088df90 SoundEffect soundDoorClose"
},
{
  "Address": 8970156,
  "AddressString": "0088dfac",
  "Name": "soundMenuOpen",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088dfac SoundEffect soundMenuOpen"
},
{
  "Address": 8970184,
  "AddressString": "0088dfc8",
  "Name": "soundMenuClose",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088dfc8 SoundEffect soundMenuClose"
},
{
  "Address": 8970212,
  "AddressString": "0088dfe4",
  "Name": "soundMenuTick",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088dfe4 SoundEffect soundMenuTick"
},
{
  "Address": 8970240,
  "AddressString": "0088e000",
  "Name": "soundShatter",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e000 SoundEffect soundShatter"
},
{
  "Address": 8970268,
  "AddressString": "0088e01c",
  "Name": "soundZombie[0x15]",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e01c SoundEffect soundZombie[0x15]"
},
{
  "Address": 8970856,
  "AddressString": "0088e268",
  "Name": "soundRoar_1",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e268 SoundEffect soundRoar_1"
},
{
  "Address": 8970884,
  "AddressString": "0088e284",
  "Name": "soundRoar_2",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e284 SoundEffect soundRoar_2"
},
{
  "Address": 8970912,
  "AddressString": "0088e2a0",
  "Name": "soundSplash_1",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e2a0 SoundEffect soundSplash_1"
},
{
  "Address": 8970940,
  "AddressString": "0088e2bc",
  "Name": "soundSplash_2",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e2bc SoundEffect soundSplash_2"
},
{
  "Address": 8970968,
  "AddressString": "0088e2d8",
  "Name": "soundDoubleJump",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e2d8 SoundEffect soundDoubleJump"
},
{
  "Address": 8970996,
  "AddressString": "0088e2f4",
  "Name": "soundRun",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e2f4 SoundEffect soundRun"
},
{
  "Address": 8971024,
  "AddressString": "0088e310",
  "Name": "soundCoins",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e310 SoundEffect soundCoins"
},
{
  "Address": 8971052,
  "AddressString": "0088e32c",
  "Name": "soundUnlock",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e32c SoundEffect soundUnlock"
},
{
  "Address": 8971080,
  "AddressString": "0088e348",
  "Name": "soundChat",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e348 SoundEffect soundChat"
},
{
  "Address": 8971108,
  "AddressString": "0088e364",
  "Name": "soundMaxMana",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e364 SoundEffect soundMaxMana"
},
{
  "Address": 8971136,
  "AddressString": "0088e380",
  "Name": "soundDrown",
  "Type": "SoundEffect",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e380 SoundEffect soundDrown"
},
{
  "Address": 8972144,
  "AddressString": "0088e770",
  "Name": "Main::musicFade",
  "Type": "void*",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e770 void* Main::musicFade"
},
{
  "Address": 8972368,
  "AddressString": "0088e850",
  "Name": "item_Main[0xc9]",
  "Type": "Item",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "0088e850 Item item_Main[0xc9]"
},
{
  "Address": 8998900,
  "AddressString": "00894ff4",
  "Name": "projectile_Main[0x200]",
  "Type": "Projectile",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "00894ff4 Projectile projectile_Main[0x200]"
},
{
  "Address": 9126016,
  "AddressString": "008b4080",
  "Name": "player[0x4]",
  "Type": "Player*",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "008b4080 Player* player[0x4]"
},
{
  "Address": 9260792,
  "AddressString": "008d4ef8",
  "Name": "imageLoader",
  "Type": "ImageLoader",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "008d4ef8 ImageLoader imageLoader"
},
{
  "Address": 9285232,
  "AddressString": "008dae70",
  "Name": "quickBG_Main",
  "Type": "u32",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "008dae70 u32 quickBG_Main"
},
{
  "Address": 137009860,
  "AddressString": "082a9ac4",
  "Name": "NPC_Main[0xc3]",
  "Type": "NPC",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "082a9ac4 NPC NPC_Main[0xc3]"
},
{
  "Address": 138056248,
  "AddressString": "083a9238",
  "Name": "recipeItems1[0x6]",
  "Type": "Item",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "083a9238 Item recipeItems1[0x6]"
},
{
  "Address": 151661576,
  "AddressString": "090a2c08",
  "Name": "_player1",
  "Type": "Player",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "090a2c08 Player _player1"
},
{
  "Address": 805320644,
  "AddressString": "300037c4",
  "Name": "Tile_Main[0x180858]",
  "Type": "Tile",
  "Other": "",
  "IsFunction": false,
  "IsCodeVariable": false,
  "IsUserDefined": true,
  "ToStringValue": "300037c4 Tile Tile_Main[0x180858]"
},
];
